export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const BREAKING_NEWS_RESULTS = 'BREAKING_NEWS_RESULTS';
export const NATIONAL_NEWS_RESULTS = 'NATIONAL_NEWS_RESULTS';
export const INTERNATIONAL_NEWS_RESULTS = 'INTERNATIONAL_NEWS_RESULTS';
